### ISSUE TITLE
Wenomechainsama

### ISSUE THREAD

**Issue by NotDevX** [itzzexcel/LInjector#13]
Tumajarbisaun
Wifenlooof
Eselifterbraun

![](https://media.tenor.com/uSk4t41mkxcAAAAd/wenomechainsama-nivar-lllll10.gif)

**Comment by ghost** [comment]
wenomechi in sama

**Comment by ghost** [comment]
tumajar bi saun

**Comment by ghost** [comment]
Wifeen loof

**Comment by ghost** [comment]
Eselifter braum

**Comment by NotDevX** [comment]
![](https://media.tenor.com/uSk4t41mkxcAAAAd/wenomechainsama-nivar-lllll10.gif)

**Comment by ghost** [comment]
![image](https://github.com/ItzzExcel/LInjector/assets/95893893/5c55fb7d-1a9c-4a90-86bd-87cbbba83104)

**Comment by itzzexcel** [comment]
![](https://media.tenor.com/uSk4t41mkxcAAAAd/wenomechainsama-nivar-lllll10.gif)

**Comment by ghost** [comment]
https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966

**Comment by ghost** [comment]
qe

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by itzzexcel** [comment]
`![](link)`

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by itzzexcel** [comment]
![](https://media.tenor.com/uSk4t41mkxcAAAAd/wenomechainsama-nivar-lllll10.gif)

**Comment by ghost** [comment]
ik

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by NotDevX** [comment]
HLPE, I CANT SEE ANYTHING + IM LAGGING

**Comment by NotDevX** [comment]
SNE D HLEP

**Comment by ghost** [comment]
SEND NUDES

**Comment by ghost** [comment]
HELP*

**Comment by itzzexcel** [comment]
we are sending bombs to devy

**Comment by NotDevX** [comment]
WTF

**Comment by ghost** [comment]
![](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by NotDevX** [comment]
> we are sending bombs to devy

minor issue

![image](https://github.com/ItzzExcel/LInjector/assets/141998343/333559ed-fd17-4b20-a099-2cf33b443190)

**Comment by ghost** [comment]
[que](https://camo.githubusercontent.com/208ab26e5b845ea4a499f9bc58f8e48ebc78a7c33d3434b1954918f7a7cd0fa9/68747470733a2f2f6d656469612e74656e6f722e636f6d2f75536b347434316d6b786341414141642f77656e6f6d65636861696e73616d612d6e697661722d6c6c6c6c6c31302e676966)

**Comment by itzzexcel** [comment]
minor issue

**Comment by NotDevX** [comment]
WE ❤️ EVERYONE HERE (except xspy, fuck that ni)

**Comment by itzzexcel** [comment]
rela

**Comment by itzzexcel** [comment]
![Excel](https://github.com/ItzzExcel/LInjector/assets/98148217/83b7ad47-b2e9-4f0a-8cd7-df00e3e82425)

**Comment by NotDevX** [comment]
![](https://cdn.discordapp.com/avatars/1038648609106833520/bebe0e4505862d0f27264551c5abef61.png?size=4096)

**Comment by NotDevX** [comment]
# now the minor issue is solved, thank you for participating in this Issue (🌋)

**Comment by ghost** [comment]
no

**Comment by itzzexcel** [comment]
ok

**Comment by NotDevX** [comment]
> no

sugma
![image](https://github.com/ItzzExcel/LInjector/assets/141998343/a257894f-ab44-44cc-b443-62f687c2197c)
