### ISSUE TITLE
Startup bug

### ISSUE THREAD

**Issue by GliitchedEntity** [itzzexcel/LInjector#5]
GUI doesn't seem to open from time to time..
The process is just sitting there doing nothing
OS: win11
Config:
{
  "autoattach": false,
  "nosplash": true,
  "metalpipe": false,
  "bamboopipe": false,
  "debug": false,
  "topmost": false,
  "discord_rpc": false,
  "options_collapsed": true,
  "hide_scriptlist": false
}

Otherwise thanks for making this project and keeping it updated, really deserves more attention <3
Fastest injection and it being open source is insane.

**Comment by NotDevX** [comment]
might wanna check task manager

**Comment by itzzexcel** [comment]
We're aware of the adonis anticheat detection.
The startup bug should be caused of the constant download of the Modules. This will be fixed soon.
